-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 11:45:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Internship_Inventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Internship_Inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Internship_Inventory` DEFAULT CHARACTER SET utf8 ;
USE `Internship_Inventory` ;

-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Login` (
  `LoginId` VARCHAR(35) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Security_Question` ENUM('FIRST MOVIE') NOT NULL,
  `Security_Answer` VARCHAR(45) NOT NULL,
  `Access_Rights` ENUM('ADMIN', 'USER') NOT NULL,
  PRIMARY KEY (`LoginId`),
  UNIQUE INDEX `LoginId_UNIQUE` (`LoginId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Person` (
  `ID` VARCHAR(15) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Cell` INT(10) NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `SSN` INT(9) NULL,
  `LoginID` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  INDEX `LoginID_idx` (`LoginID` ASC),
  CONSTRAINT `LoginID`
    FOREIGN KEY (`LoginID`)
    REFERENCES `Internship_Inventory`.`Login` (`LoginId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Student` (
  `StudentID` VARCHAR(15) NOT NULL,
  `Semester` VARCHAR(45) NULL,
  `Major` VARCHAR(45) NULL,
  `Minor` VARCHAR(45) NULL,
  `GraduationYear` YEAR NULL,
  `EnrollmentYear` YEAR NULL,
  `GPA` DECIMAL NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `studentId`
    FOREIGN KEY (`StudentID`)
    REFERENCES `Internship_Inventory`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Company` (
  `CompanyId` VARCHAR(15) NOT NULL,
  `CompanyName` VARCHAR(45) NOT NULL DEFAULT 'Anonymous',
  `Address` VARCHAR(45) NOT NULL,
  `Cell` INT(10) NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Industry` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CompanyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Internship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Internship` (
  `InternshipId` VARCHAR(15) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `Location` VARCHAR(20) NULL DEFAULT 'Not Decided',
  `Description` VARCHAR(90) NULL,
  `HoursPerWeek` INT NOT NULL,
  `NoOfOpenings` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `PaidYorN` TINYINT(0) NOT NULL,
  `CompanyID` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`InternshipId`),
  INDEX `CompanyID_idx` (`CompanyID` ASC),
  CONSTRAINT `CompanyID`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `Internship_Inventory`.`Company` (`CompanyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Application` (
  `ApplicationID` INT NOT NULL,
  `HireOrNot` ENUM('pending', 'yes', 'no') NOT NULL DEFAULT 'pending',
  `StudentID` VARCHAR(15) NOT NULL,
  `InternshipID` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ApplicationID`),
  UNIQUE INDEX `applicationID_UNIQUE` (`ApplicationID` ASC),
  INDEX `studentId_idx` (`StudentID` ASC),
  CONSTRAINT `studentId`
    FOREIGN KEY (`StudentID`)
    REFERENCES `Internship_Inventory`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InternshipID`
    FOREIGN KEY ()
    REFERENCES `Internship_Inventory`.`Internship` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Supervisor` (
  `SupervisorID` VARCHAR(15) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `WorkPhone` INT(10) NULL,
  `OfficeAddress` VARCHAR(90) NULL,
  `CompanyID` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`SupervisorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Placement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Placement` (
  `PlacementID` INT NOT NULL,
  `SupervisorID` VARCHAR(15) NOT NULL DEFAULT 'ToAssign',
  `Notes` VARCHAR(45) NULL,
  PRIMARY KEY (`PlacementID`),
  INDEX `SupervisorID_idx` (`SupervisorID` ASC),
  CONSTRAINT `PlacementID`
    FOREIGN KEY (`PlacementID`)
    REFERENCES `Internship_Inventory`.`Application` (`ApplicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SupervisorID`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `Internship_Inventory`.`Supervisor` (`SupervisorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Paperwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Paperwork` (
  `PlacementId` INT NOT NULL,
  `StudentEvaluation` TINYINT(1) NULL DEFAULT Yes or No,
  `SupervisorEvaluation` TINYINT(1) NOT NULL DEFAULT Yes or No,
  `CompanyInfo` TINYINT(1) NOT NULL DEFAULT Yes or No,
  `StudentInfo` TINYINT(1) NOT NULL DEFAULT Yes or No,
  PRIMARY KEY (`PlacementId`),
  UNIQUE INDEX `PlacementId_UNIQUE` (`PlacementId` ASC),
  CONSTRAINT `PlacementID`
    FOREIGN KEY (`PlacementId`)
    REFERENCES `Internship_Inventory`.`Placement` (`PlacementID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Employee` (
  `EmployeeID` VARCHAR(15) NOT NULL,
  `OfficePhone` VARCHAR(45) NULL,
  `OfficeAdd` VARCHAR(255) NULL,
  PRIMARY KEY (`EmployeeID`),
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `Internship_Inventory`.`Person` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Administrator` (
  `AdminID` VARCHAR(15) NOT NULL,
  `Shift` VARCHAR(45) NULL,
  PRIMARY KEY (`AdminID`),
  CONSTRAINT `AdminID`
    FOREIGN KEY (`AdminID`)
    REFERENCES `Internship_Inventory`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Facaulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Facaulty` (
  `FacID` VARCHAR(15) NOT NULL,
  `Dept` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`FacID`),
  CONSTRAINT `FacID`
    FOREIGN KEY (`FacID`)
    REFERENCES `Internship_Inventory`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`Skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`Skills` (
  `SkillID` VARCHAR(15) NOT NULL,
  `SkillDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`SkillID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`InternshipSkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`InternshipSkill` (
  `SkillID` VARCHAR(15) NOT NULL,
  `InternshipID` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`SkillID`, `InternshipID`),
  INDEX `InternshipId_idx` (`InternshipID` ASC),
  CONSTRAINT `InternshipId`
    FOREIGN KEY (`InternshipID`)
    REFERENCES `Internship_Inventory`.`Internship` (`InternshipId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SkillId`
    FOREIGN KEY (`SkillID`)
    REFERENCES `Internship_Inventory`.`Skills` (`SkillID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`PaidIntern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`PaidIntern` (
  `InternshipID` VARCHAR(15) NOT NULL,
  `TotalSalary` DOUBLE NULL,
  `WorkType` VARCHAR(45) NULL,
  PRIMARY KEY (`InternshipID`),
  CONSTRAINT `InternshipID`
    FOREIGN KEY (`InternshipID`)
    REFERENCES `Internship_Inventory`.`Internship` (`InternshipId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Internship_Inventory`.`UnpaidIntern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internship_Inventory`.`UnpaidIntern` (
  `InternshipID` VARCHAR(15) NOT NULL,
  `AcademicCredit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`InternshipID`),
  CONSTRAINT `InternshipID`
    FOREIGN KEY (`InternshipID`)
    REFERENCES `Internship_Inventory`.`Internship` (`InternshipId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Internship_Inventory`;

DELIMITER $$
USE `Internship_Inventory`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Internship_Inventory`.`Administrator_BEFORE_INSERT` BEFORE INSERT ON `Administrator` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
